[package]
name = "nbfc-config"
version = "0.7.2"
edition = "2021"
license = "MPL-2.0"

[dependencies]
quick-xml = "0.22.0"
serde = { version = "1.0.130", features = ["derive"] }

[dev-dependencies]
serde_json = "1.0.69"
