[package]
name = "nbfc-config"
version = "0.4.0"
edition = "2018"
license = "MPL-2.0"

[dependencies]
quick-xml = "0.22.0"
schemars = "0.8.6"
serde = { version = "1.0.130", features = ["derive"] }

[build-dependencies]
schemars = "0.8.6"
serde = "1.0.130"
serde_json = "1.0.68"
