name: test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install required libraries
        run: sudo apt-get update && sudo apt-get install -y libdbus-1-dev libgtk-3-dev

      - uses: actions/checkout@v2

      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-deny
          version: latest

      - uses: actions-rs/cargo@v1
        with:
          command: deny
          args: check

      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all --all-features
