name: Build releases
on:
  push:
    tags:
      - "*.*.*"

jobs:
  create_release:
    runs-on: ubuntu-latest
    name: Create release
    outputs:
      upload_url: ${{ steps.create.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/create-release@v1
        id: create
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ format('v{0}', github.ref) }}

  deb:
    runs-on: ubuntu-latest
    name: Build package
    needs: create_release
    steps:
      - name: Install required packages
        run: sudo apt update && sudo apt install -y libdbus-1-dev build-essential debhelper dh-make fakeroot

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions/checkout@v2

      - name: Build the package
        run: dpkg-buildpackage -us -uc

      - name: Find Debian package
        id: find_deb
        run: |
          path=$(find .. -name '*.deb' -print -quit)
          echo "::set-output name=path::$path"
          echo "::set-output name=name::$(basename $path)"

      - name: Upload Debian package
        id: upload-deb
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ${{ steps.find_deb.outputs.path }}
          asset_name: ${{ steps.find_deb.outputs.name }}
          asset_content_type: application/vnd.debian.binary-package
