name: Build releases
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  create_release:
    runs-on: ubuntu-latest
    name: Create release
    steps:
      - uses: actions/checkout@v2

      - uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Install required packages
        run: sudo apt-get update && sudo apt-get install -y libdbus-1-dev build-essential debhelper dh-make fakeroot pandoc

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions/checkout@v2

      - name: Upload build folder
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: target/

  make-archive:
    runs-on: ubuntu-latest
    name: Build archive
    needs: [create_release, build]
    env:
      DESTDIR: ${{ format('fancy-{0}', github.ref) }}
      OUTPUT_FILE: ${{ format('fancy-{0}.tar.xz', github.ref) }}

    steps:
      - name: Install required packages
        run: sudo apt-get update && sudo apt-get install -y libdbus-1-dev build-essential debhelper dh-make fakeroot pandoc

      - uses: actions/checkout@v2

      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: build

      - name: Build
        run: make && make install

      - name: Make archive
        run: tar czf $OUTPUT_FILE $DESTDIR

      - name: Upload archive
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ${{ env.OUTPUT_FILE }}

  make-deb:
    runs-on: ubuntu-latest
    name: Build Debian package
    needs: [create_release, build]
    steps:
      - name: Install required packages
        run: sudo apt-get update && sudo apt-get install -y libdbus-1-dev build-essential debhelper dh-make fakeroot pandoc

      - uses: actions/checkout@v2

      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: build

      - name: Build the package
        run: dpkg-buildpackage -us -uc

      - name: Upload Debian package
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: "../*.deb"
