name: Build releases
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  create_release:
    runs-on: ubuntu-latest
    name: Create release
    steps:
      - uses: actions/checkout@v2

      - uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  make-archive:
    runs-on: ubuntu-latest
    name: Build archive
    needs: create_release
    env:
      DESTDIR: ${{ format('fancy-{0}', github.ref) }}
      OUTPUT_FILE: ${{ format('fancy-{0}.tar.xz', github.ref) }}

    steps:
      - name: Install required packages
        run: sudo apt-get update && sudo apt-get install -y libdbus-1-dev build-essential debhelper dh-make fakeroot pandoc

      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Create DESTDIR folder
        run: mkdir -p $DESTDIR

      - name: Build
        run: make && make install

      - name: Make archive
        run: tar czf $OUTPUT_FILE $DESTDIR

      - name: Upload archive
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ${{ env.OUTPUT_FILE }}

  make-rpm:
    runs-on: ubuntu-latest
    container: fedora:latest
    name: Build RPM package
    needs: create_release
    steps:
      - name: Install required packages
        run: "dnf install -y rpkg copr-cli && dnf builddep -y $(rpkg spec | cut -d':' -f2 | tr -d '[:space:]')"

      - uses: actions/checkout@v2

      - name: Save COPR config
        env:
          COPR_CONFIG_TOKEN: ${{ secrets.COPR_CONFIG_TOKEN }}
        run: |
          mkdir -p $HOME/.config/
          echo "$COPR_CONFIG_TOKEN" > $HOME/.config/copr

      - name: Build package for COPR
        run: rpkg build Fancy

      - name: Set tempdir
        run: tempdir=$(mktemp -d) >> $GITHUB_ENV

      - name: Build package for GitHub
        run: |
          "rpkg local --outdir=${{ env.tempdir }}"

      - name: Upload package
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: "${{ env.tempdir }}/**/*.rpm"

  make-deb:
    runs-on: ubuntu-latest
    name: Build Debian package
    needs: create_release
    steps:
      - name: Install required packages
        run: sudo apt-get update && sudo apt-get install -y libdbus-1-dev build-essential debhelper fakeroot pandoc

      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build the package
        run: dpkg-buildpackage -us -uc

      - name: Upload Debian package
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: "../*.deb"
