name: Release workflow
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install -y libdbus-1-dev
      - uses: action-rs/cargo@v1
        with:
          command: build
          args: --release
